travis:
  secure:
    BINSTAR_TOKEN: KUyqJeH8MUdZWSmFbJ2xYMp1yjBW3yQGIJY3R8hfU0nfwMrD0H6mFPaeaYaP5OnTXpv/0KsRXZvoXYtjpR+4YEg5b56MlcV2ayU+6YrskjmQommbfwcKt7lreQWkgLWjMTW+Rz8LNW/hXfo4HwsxD5OI3mC3UCoAFSES3O+4niyvOzoWyUdQ1aCRkP1+7F3VVUR5zgNHaHapMWXApRFNIO3Nt+Y1iz/uV7j0hTTPbqvxRJV+5z9wY2M4M6QN93b3ryLsekC8lUrHfs8HieyenX99iisjUIajysIlbKQ1GvCn9bXVLDSBVphFWOGxlkpRL4VoMEITw4LOt8xHjLPDFloIG/kbjJGnpByNZYcHiLMuPt+4oEDMPHCg18EjOa1I4ZHCDhdhncXA3EBTJyYyVTBfoQtQSVQXkDyyV0+jc47uPAKN4HWhcFPgimOzyDDTJTCb/8SZ3aUv5mpsATKdn8N4CpN4r/g4o5H/H3YrxVb1+g1hqtZ4WB2ChKQ5l/LM4mgsKA4oBn2ZwvpFy6MukyZeat78+76jG7MWr4ohdFPhTMkPGm7EXzh2K2zItaQ2n7XYxBP7CLlAznttES72om16VaB53I9K/Oyg44OUdvdgXFGA9CnKrMErALJkn7OVDdEVnfp7T1fpA5JtFVD1hb08BSrHUA8FGzj6KpAGOjI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
