appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UVILOuvvlFzNaGphTiGI2UzomFSvr+I6YLUOLf7h8kJwRQge2pihKDT7Jo+pwyj9f6sR4KIHHLKdOvp0wb/L5i7ES/2K/tLibimzjvFOGEnKisGeWsPw0V8fnmI495z5yzSeWAhZCZt4/lMaMQT4/WZ7gkBQNs71/Sy7DsWlIkdztdiEJE+xMuZeUfC43gWKO+voESD1/f706J4yK5yLlbolyVXWW9BnYuUm4UG5Iiuzu8Yk07YwCaxh2Ty94GJJLVP/nyNsNefelAOwPqmby9FbTEVcoHxr9Bk8n3vEixjKzYo9ecHvu3MLcvBOx9zFFLqqPuvomIIKK28ds1p0ObHki/bzQOUZaGDYiXr57BRIvMLEqNUedMYjrN985anmhufszfvhr5/RsfA9AHvTINVQsvOUt6fPugzcg9AP8Uh/p6GKy3Xe5RvMRuJbCwZP5eIS1YM2XKpYnrLfJ0P2QyrN93oqsmVPdzhMYFzKVu1Ldtu+EL315BCxDLA1AlPK0G+ktsW9PbSEkaA4i1hNDM2KslujFllvzBtbmhSI6oxHPC0VotEuKRt7xtC/ZEUHWVinpPKKC0vKn6a7nrZ1kK5xo3s3GZ/Z4981qKz70j9cWsdELm5D5d2fMAfGmglztcw19QNX4O6mcxwO0fEG4VLIk3H5MDMlV7pnI4tQrSY=}
provider:
  win: azure
bot:
  automerge: true
