travis:
  secure:
    BINSTAR_TOKEN: zhDhv2Qlz+KDGMMEcfkgU6dfyjju6qoWtrtFpMwcefeQlNR6K5Hb9qkSI/RtBVcd1Oug1peVFjJk9vibIBCyqgBt66OkQ9NoNiJ/4seJBEXH62RyIiwC8E7uY8r6+lKEt6mWEwIge3hgwze9gzJ1IT1uaBd7+fvJ+rQ/Df31qzPsareDlBoDLSkJAckLCpiLDgTLbxQBX13QYSOVeMClTJS+G484HtVhRAxQhxk/qnoAtaelSaMNzu3EYBFhVbYW+OTKi9gfi7Hk9uNphjsV4K6ZKagoMfvV2ugOmWdnNKCFmSnqNotfTOZmU6LKjAAQJVzfAFvMj5JuLEzqudVwIXLymh0oQ9wn5vUcFmGM15PNkGJFzyNqvpMVYMcPQCZ9kFW1+ktnlrS+/9jtEu7dc1St9uR0AOGBoQoMoIUN5UiZ0XbNHE6Hp5ZhMvBuhPCx0DtODFD6xN3GE8EaB43GCGzNVnULeNKPa9US6NWvULSkwCu3IUdk8K3huhbR6Kt0Le67t1sYwmW3XQXG96Z4glsJ4YuXmykc3RTJbZPjQgl10zYyTWOF0ZsaaMSdwpNLgMTOq0bI+bjYv3TdUgC3sqMnmsflHh99FrWVyPzXad/EkKkGfpHvr1gNEbORLKc4FU3w9ID7TIZoq2wFgjLDXyhi5PymN9Jiazt9TKlGMBA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
