travis:
  secure:
    BINSTAR_TOKEN: mK36I+MfeItUCPRt7Za5naiTpyguk/AgJpkvexUriPcCU3FQXcMVUAY8CmTL1muz7/XbSmj2eL67UScAIRkofPzvvWaklznDDN0iQzZ+u8ZKyUeUsvD5umatHsg0l91dPBosOLpn0shb5ZODqRPt/ke39KK31A0rZ2FrmmmaVQwiL6eyzk0NdeIT0nKOdn0GmUBlGS6MNy3tLvAxTCLl4H9MF55kvPK3AH8Q8Maf3FHHTXGpPDjPGCXj/Ks+c6P5sZkBsW2osYnZ1k0mj7wURJ1YPeIr6gwcLFTjbmCHYyOrSNB7d3tLRN5UvDXb2uwValH21dIa+vU24B0U7oz/YvmaLhbwH2ZDKjBLmMIjqVEhBpPv+FClcaXAW7aZIKJtFfCI/TUuu+ig15yrUj3Zi0Q8H2N9TBPu0Ki/5qaM7nFiIL0RXsPbr40jwJv3xtXx+eDNsr6NfHoaYKSZMhElHx3TJEF7b1y2KMyoizyDSlmdtmgVP9JnJxcopE7cxolOTQP6lU9G/PSWqAdApwrz7fVjsWgQxoA3OqVXhR2ukufotBrRBhnSaJrkf7BHaiiulhURhMBjKzpcmBLmxG/KqfN7kOWpVdttJm9fVwaFX7elL+cLnzpfUKUS9eTcIdHOW/Hs8ElEnI/vFj2jd4GzP/2nDz2Vo3TP2s9hi+B806w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
