travis:
  secure:
    BINSTAR_TOKEN: Jw3UNKp4SHUNcM6h3ySEx8r6VEbIhzRbb+C35dmFC1AwaHJ4DKxtg21RATEdWupGy3NXTWqqDU8I8xSxbfWMsUngEZrd7LbtpM6PoD8u4ld19wHSCFK+UbNYalcta4sAodZLThtAReDjV38GhzgnrKR/74bPSZJnTqyCwrjpx4B9aWyl5HzIvsscy9BBPzDv79zh5RreTnmewuPIVdWTq4Ssr78kkIhIFbINk/MYHsHbIGxU1lejZGkX2P5B/vuYLJ9WTq742XWReYNJ4tgofa6MzYqtECX+E8zF/e6mskqCSOeY9RKVAvr0+cDdSu1JQ8TFzFiHMhzznTdt10lYUsPSm10yx3s6Vjjxmk0eloQU8h+CdiUOYqY6g7WP2Esr5wndyP38bkP9AWGwGgHOvyduOhczEnsxvAh7DRWlZzK2zm22k5/n04qOVk2plUYiXvAyV9wpEa7rEY9i4W8WUSERientDKPqzY6BIZu68fLeA5sy0g/KWaJsR50yOb8YrYuDq8HvW5AMAnlW+HlvZwjCVOHQu02kjrpSn5BwM+lAOTHUws2K2ITMQyMk3j1279AS7IdbwQa51byZQR9PP4RI6ZV77CU6ZZ3kYuFxqLnxtlzOhnbG+sEqfdrkWrAG2ijqfV0JuBCVIL8vqnmGsbzSI/Lg30pcqofItPFVUv0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
